version: "3.4"

services:
  app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    restart: unless-stopped
    environment:
      _JAVA_OPTIONS: ${JAVA_OPTIONS}
    env_file:
      - .env
    entrypoint: java -jar app.jar ${OPERATION_MODE}

